serverUrl: http://biominds.pl
shortTitle: BioMinds XR
title: BioMinds Healtcare Sp. z o.o.
description: The only XR rehabilitation system combining movement, cognitive and psychological therapies
masterUserDisplayName: BioMinds
masterLanguage: en
languages: "en->English,pl->Polish"
